debug:
  update_interval: 10s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 10s
    filters:
       - median:
          window_size: 3
          send_every: 1
          send_first_at: 1

  - platform: uptime
    name: Uptime Sensor

  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

text_sensor:
  - platform: version
    name: "ESPHome Version"

  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
      
  #Wifi info
  - platform: wifi_info
    ssid:
      name: ESP Connected SSID
    ip_address:
      name: ESP IP Address
    mac_address:
      name: ESP Mac Wifi Address
    bssid:
      name: ESP Connected BSSID
    scan_results:
      name: ESP Latest Scan Results
